# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/charan010/flux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/charan010/flux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charan010/flux/CMakeFiles /home/charan010/flux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charan010/flux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flux

# Build rule for target.
flux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux
.PHONY : flux

# fast build rule for target.
flux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/build
.PHONY : flux/fast

# target to build an object file
bit_io.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/bit_io.o
.PHONY : bit_io.o

# target to preprocess a source file
bit_io.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/bit_io.i
.PHONY : bit_io.i

# target to generate assembly for a file
bit_io.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/bit_io.s
.PHONY : bit_io.s

# target to build an object file
helper.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/helper.o
.PHONY : helper.o

# target to preprocess a source file
helper.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/helper.i
.PHONY : helper.i

# target to generate assembly for a file
helper.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/helper.s
.PHONY : helper.s

# target to build an object file
huffman.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/huffman.o
.PHONY : huffman.o

# target to preprocess a source file
huffman.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/huffman.i
.PHONY : huffman.i

# target to generate assembly for a file
huffman.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/huffman.s
.PHONY : huffman.s

# target to build an object file
main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/main.s
.PHONY : main.s

# target to build an object file
pipeline/chunk.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk.o
.PHONY : pipeline/chunk.o

# target to preprocess a source file
pipeline/chunk.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk.i
.PHONY : pipeline/chunk.i

# target to generate assembly for a file
pipeline/chunk.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk.s
.PHONY : pipeline/chunk.s

# target to build an object file
pipeline/chunk_buffer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk_buffer.o
.PHONY : pipeline/chunk_buffer.o

# target to preprocess a source file
pipeline/chunk_buffer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk_buffer.i
.PHONY : pipeline/chunk_buffer.i

# target to generate assembly for a file
pipeline/chunk_buffer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/chunk_buffer.s
.PHONY : pipeline/chunk_buffer.s

# target to build an object file
pipeline/coordinator.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/coordinator.o
.PHONY : pipeline/coordinator.o

# target to preprocess a source file
pipeline/coordinator.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/coordinator.i
.PHONY : pipeline/coordinator.i

# target to generate assembly for a file
pipeline/coordinator.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/pipeline/coordinator.s
.PHONY : pipeline/coordinator.s

# target to build an object file
progress/progress_bar.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_bar.o
.PHONY : progress/progress_bar.o

# target to preprocess a source file
progress/progress_bar.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_bar.i
.PHONY : progress/progress_bar.i

# target to generate assembly for a file
progress/progress_bar.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_bar.s
.PHONY : progress/progress_bar.s

# target to build an object file
progress/progress_renderer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_renderer.o
.PHONY : progress/progress_renderer.o

# target to preprocess a source file
progress/progress_renderer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_renderer.i
.PHONY : progress/progress_renderer.i

# target to generate assembly for a file
progress/progress_renderer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/progress/progress_renderer.s
.PHONY : progress/progress_renderer.s

# target to build an object file
threadpool/threadpool.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/threadpool/threadpool.o
.PHONY : threadpool/threadpool.o

# target to preprocess a source file
threadpool/threadpool.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/threadpool/threadpool.i
.PHONY : threadpool/threadpool.i

# target to generate assembly for a file
threadpool/threadpool.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flux.dir/build.make CMakeFiles/flux.dir/threadpool/threadpool.s
.PHONY : threadpool/threadpool.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... flux"
	@echo "... bit_io.o"
	@echo "... bit_io.i"
	@echo "... bit_io.s"
	@echo "... helper.o"
	@echo "... helper.i"
	@echo "... helper.s"
	@echo "... huffman.o"
	@echo "... huffman.i"
	@echo "... huffman.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pipeline/chunk.o"
	@echo "... pipeline/chunk.i"
	@echo "... pipeline/chunk.s"
	@echo "... pipeline/chunk_buffer.o"
	@echo "... pipeline/chunk_buffer.i"
	@echo "... pipeline/chunk_buffer.s"
	@echo "... pipeline/coordinator.o"
	@echo "... pipeline/coordinator.i"
	@echo "... pipeline/coordinator.s"
	@echo "... progress/progress_bar.o"
	@echo "... progress/progress_bar.i"
	@echo "... progress/progress_bar.s"
	@echo "... progress/progress_renderer.o"
	@echo "... progress/progress_renderer.i"
	@echo "... progress/progress_renderer.s"
	@echo "... threadpool/threadpool.o"
	@echo "... threadpool/threadpool.i"
	@echo "... threadpool/threadpool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

